# -*- coding: utf-8 -*-
"""AryanLab.

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hfTfDEUNL8xhw6axa4e7spef10e1HXts
"""

print("Aryan Godse, A71004817007, BCA1707, Sem 6")
print("This python file has been successfully executed")
print("this file has been created to demonstrate the practical execution for jenkins Github integration")
print("Date 3-05-2021")